[package]
name = "excel_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.10"
lazy_static = "1.4"
eframe = "0.24"
egui = "0.24"
winit = "=0.28.7"
objc2 = "=0.5.1"
icrate = "=0.0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
